apiVersion: v1
kind: Service 
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None #for headless service there is no cluster IP
  selector:
    project: expense
    component: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 3306 #service port 
    targetPort: 3306 # container port
--- 
apiVersion: v1
kind: Service 
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    project: expense
    component: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 3306 #service port 
    targetPort: 3306 # container port
--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      project: expense
      component: mysql
      tier: db
  serviceName: "mysql-headless" #this is the headless service should be mentioned for statefulset
  replicas: 2 # by default is 1
  template: # Pod definition 
    metadata:
      labels:
        project: expense
        component: mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: mahadevan045/mysql:v1
        ports:
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  # This is PVC definition ,directly mentioned here
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "expense-ebs"
      resources:
        requests:
          storage: 1Gi